# Generated by Django 4.0.1 on 2022-01-30 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_fname', models.CharField(default='unknown', max_length=10, verbose_name='fname')),
                ('user_lname', models.CharField(default='unknown', max_length=10, verbose_name='lname')),
                ('user_usrname', models.CharField(default='unknown', max_length=30, unique=True, verbose_name='user_name')),
                ('user_email', models.EmailField(default='email@email.com', max_length=254, unique=True)),
                ('user_password', models.CharField(max_length=50)),
            ],
        ),
    ]
