# Generated by Django 4.0.1 on 2022-01-30 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intake',
            fields=[
                ('intake_id', models.AutoField(primary_key=True, serialize=False)),
                ('intake_name', models.CharField(max_length=10)),
                ('intake_start_date', models.DateField()),
                ('intake_end_date', models.DateField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_fname', models.CharField(default='unknown', max_length=10, verbose_name='fname')),
                ('student_lname', models.CharField(default='unknown', max_length=10)),
                ('student_email', models.EmailField(default='email@email.com', max_length=254, unique=True)),
                ('student_gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], default='male', max_length=10)),
            ],
        ),
    ]
